// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmI7ZIJhSG2WxhdBRzdA5WtV5iuClCImk',
    appId: '1:654854303649:web:f138d4ee02aab835bce5e0',
    messagingSenderId: '654854303649',
    projectId: 'speach-disorder',
    authDomain: 'speach-disorder.firebaseapp.com',
    storageBucket: 'speach-disorder.firebasestorage.app',
    measurementId: 'G-Z5MFXS9GYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEzR2_Leyh244-l8jOI39Bt-18hxeG06I',
    appId: '1:654854303649:android:18c003ce89eef44abce5e0',
    messagingSenderId: '654854303649',
    projectId: 'speach-disorder',
    storageBucket: 'speach-disorder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmQE89ChoG6YBvtu3G71vehm8RxwJ8VYo',
    appId: '1:654854303649:ios:2055ae943862e4bdbce5e0',
    messagingSenderId: '654854303649',
    projectId: 'speach-disorder',
    storageBucket: 'speach-disorder.firebasestorage.app',
    iosBundleId: 'com.example.speechTherapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmQE89ChoG6YBvtu3G71vehm8RxwJ8VYo',
    appId: '1:654854303649:ios:2055ae943862e4bdbce5e0',
    messagingSenderId: '654854303649',
    projectId: 'speach-disorder',
    storageBucket: 'speach-disorder.firebasestorage.app',
    iosBundleId: 'com.example.speechTherapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmI7ZIJhSG2WxhdBRzdA5WtV5iuClCImk',
    appId: '1:654854303649:web:558063a5147929b2bce5e0',
    messagingSenderId: '654854303649',
    projectId: 'speach-disorder',
    authDomain: 'speach-disorder.firebaseapp.com',
    storageBucket: 'speach-disorder.firebasestorage.app',
    measurementId: 'G-DK2F3P8PQF',
  );
}
